import hljs from "highlight.js";

const Constants = {
  languages: hljs.listLanguages(),
  formats: ["svg", "png", "jpeg"],
  types: ["conic", "linear", "radial"],
  paddings: {
    "16px": "p-4",
    "32px": "p-8",
    "64px": "p-16",
    "128px": "p-32",
  },
  directions: [
    "top",
    "top-right",
    "right",
    "bottom-right",
    "bottom",
    "bottom-left",
    "left",
    "top-left",
  ],
  sizes: {
    post: { width: 960, height: 540 },
    header: { width: 1500, height: 500 },
    thumbnail: { width: 1280, height: 720 },
    "story-reel": { width: 540, height: 960 },
    "instagram-post": { width: 720, height: 720 },
    "full-screen": { width: "100%", height: "100%" },
    auto: { width: "max-content", height: "max-content" },
  },
  colors: [
    "bg-blue-500 from-blue-500 to-blue-300 ring-1 ring-blue-500 dark:from-blue-950 dark:to-blue-700 dark:ring-blue-950",
    "bg-green-500 from-green-500 to-green-300 ring-1 ring-green-500 dark:from-green-950 dark:to-green-700 dark:ring-green-950",
    "bg-rose-500 from-rose-500 to-rose-300 ring-1 ring-rose-500 dark:from-rose-950 dark:to-rose-700 dark:ring-rose-950",
    "bg-indigo-500 from-indigo-500 to-indigo-300 ring-1 ring-indigo-500 dark:from-indigo-950 dark:to-indigo-700 dark:ring-indigo-950",
    "bg-violet-500 from-violet-500 to-violet-300 ring-1 ring-violet-500 dark:from-violet-950 dark:to-violet-700 dark:ring-violet-950",
    "bg-purple-500 from-purple-500 to-purple-300 ring-1 ring-purple-500 dark:from-purple-950 dark:to-purple-700 dark:ring-purple-950",
    "bg-lime-500 from-lime-500 to-lime-300 ring-1 ring-lime-500 dark:from-lime-950 dark:to-lime-700 dark:ring-lime-950",
    "bg-yellow-500 from-yellow-500 to-yellow-300 ring-1 ring-yellow-500 dark:from-yellow-950 dark:to-yellow-700 dark:ring-yellow-950",
    "bg-sky-500 from-sky-500 to-sky-300 ring-1 ring-sky-500 dark:from-sky-950 dark:to-sky-700 dark:ring-sky-950",
    "bg-teal-500 from-teal-500 to-teal-300 ring-1 ring-teal-500 dark:from-teal-950 dark:to-teal-700 dark:ring-teal-950",
    "bg-cyan-500 from-cyan-500 to-cyan-300 ring-1 ring-cyan-500 dark:from-cyan-950 dark:to-cyan-700 dark:ring-cyan-950",
    "bg-amber-500 from-amber-500 to-amber-300 ring-1 ring-amber-500 dark:from-amber-950 dark:to-amber-700 dark:ring-amber-950",
    "bg-emerald-500 from-emerald-500 to-emerald-300 ring-1 ring-emerald-500 dark:from-emerald-950 dark:to-emerald-700 dark:ring-emerald-950",
    "bg-fuchsia-500 from-fuchsia-500 to-fuchsia-300 ring-1 ring-fuchsia-500 dark:from-fuchsia-950 dark:to-fuchsia-700 dark:ring-fuchsia-950",
    "bg-orange-500 from-orange-500 to-orange-300 ring-1 ring-orange-500 dark:from-orange-950 dark:to-orange-700 dark:ring-orange-950",
    "bg-slate-500 from-slate-500 to-slate-300 ring-1 ring-slate-500 dark:from-slate-950 dark:to-slate-700 dark:ring-slate-950",
    "bg-stone-500 from-stone-500 to-stone-300 ring-1 ring-stone-500 dark:from-stone-950 dark:to-stone-700 dark:ring-stone-950",
    "bg-sky-400 from-sky-400 to-lime-400 ring-1 ring-sky-400 dark:from-sky-700 dark:to-lime-700 dark:ring-sky-700",
    "bg-sky-400 from-sky-400 to-pink-400 ring-1 ring-sky-400 dark:from-sky-700 dark:to-pink-800 dark:ring-sky-700",
    "bg-lime-300 from-lime-300 to-orange-300 ring-1 ring-lime-300 dark:from-lime-700 dark:to-orange-600 dark:ring-lime-700",
    "bg-green-400 from-green-400 to-teal-400 ring-1 ring-green-400 dark:from-green-700 dark:to-teal-600 dark:ring-green-700",
    "bg-green-400 from-green-400 to-amber-300 ring-1 ring-green-400 dark:from-green-700 dark:to-amber-600 dark:ring-green-700",
    "bg-sky-300 from-sky-300 to-pink-300 ring-1 ring-sky-300 dark:from-sky-700 dark:to-pink-600 dark:ring-sky-700",
    "bg-green-400 from-green-400 to-sky-400 ring-1 ring-green-400 dark:from-green-600 dark:to-sky-500 dark:ring-green-600",
    "bg-emerald-400 from-emerald-400 to-sky-300 ring-1 ring-emerald-400 dark:from-emerald-700 dark:to-sky-600 dark:ring-emerald-700",
    "bg-lime-300 from-lime-300 to-green-400 ring-1 ring-lime-300 dark:from-lime-700 dark:to-green-600 dark:ring-lime-700",
    "bg-cyan-300 from-cyan-300 to-emerald-400 ring-1 ring-cyan-300 dark:from-cyan-800 dark:to-emerald-700 dark:ring-cyan-800",
    "bg-cyan-200 from-cyan-200 to-pink-400 ring-1 ring-cyan-200 dark:from-cyan-700 dark:to-pink-600 dark:ring-cyan-700",
    "bg-red-400 from-red-400 to-orange-300 ring-1 ring-red-400 dark:from-red-600 dark:to-orange-500 dark:ring-red-600",
    "bg-orange-400 from-orange-400 to-orange-100 ring-1 ring-orange-400 dark:from-red-700 dark:to-red-600 dark:ring-red-700",
    "bg-orange-200 from-orange-200 to-sky-400 ring-1 ring-orange-200 dark:from-orange-800 dark:to-sky-700 dark:ring-orange-800",
    "bg-orange-200 from-orange-200 to-red-300 ring-1 ring-orange-200 dark:from-orange-600 dark:to-red-500 dark:ring-orange-600",
    "bg-lime-200 from-lime-200 to-pink-400 ring-1 ring-lime-200 dark:from-lime-600 dark:to-pink-500 dark:ring-lime-600",
    "bg-sky-200 from-sky-200 to-pink-300 ring-1 ring-sky-200 dark:from-sky-600 dark:to-pink-500 dark:ring-sky-600",
  ],
  highlights: [
    "a11y-dark",
    "a11y-dark.min",
    "a11y-light",
    "a11y-light.min",
    "agate",
    "agate.min",
    "an-old-hope",
    "an-old-hope.min",
    "androidstudio",
    "androidstudio.min",
    "arduino-light",
    "arduino-light.min",
    "arta",
    "arta.min",
    "ascetic",
    "ascetic.min",
    "atom-one-dark",
    "atom-one-dark-reasonable",
    "atom-one-dark-reasonable.min",
    "atom-one-dark.min",
    "atom-one-light",
    "atom-one-light.min",
    "base16/3024",
    "base16/3024.min",
    "base16/apathy",
    "base16/apathy.min",
    "base16/apprentice",
    "base16/apprentice.min",
    "base16/ashes",
    "base16/ashes.min",
    "base16/atelier-cave",
    "base16/atelier-cave-light",
    "base16/atelier-cave-light.min",
    "base16/atelier-cave.min",
    "base16/atelier-dune",
    "base16/atelier-dune-light",
    "base16/atelier-dune-light.min",
    "base16/atelier-dune.min",
    "base16/atelier-estuary",
    "base16/atelier-estuary-light",
    "base16/atelier-estuary-light.min",
    "base16/atelier-estuary.min",
    "base16/atelier-forest",
    "base16/atelier-forest-light",
    "base16/atelier-forest-light.min",
    "base16/atelier-forest.min",
    "base16/atelier-heath",
    "base16/atelier-heath-light",
    "base16/atelier-heath-light.min",
    "base16/atelier-heath.min",
    "base16/atelier-lakeside",
    "base16/atelier-lakeside-light",
    "base16/atelier-lakeside-light.min",
    "base16/atelier-lakeside.min",
    "base16/atelier-plateau",
    "base16/atelier-plateau-light",
    "base16/atelier-plateau-light.min",
    "base16/atelier-plateau.min",
    "base16/atelier-savanna",
    "base16/atelier-savanna-light",
    "base16/atelier-savanna-light.min",
    "base16/atelier-savanna.min",
    "base16/atelier-seaside",
    "base16/atelier-seaside-light",
    "base16/atelier-seaside-light.min",
    "base16/atelier-seaside.min",
    "base16/atelier-sulphurpool",
    "base16/atelier-sulphurpool-light",
    "base16/atelier-sulphurpool-light.min",
    "base16/atelier-sulphurpool.min",
    "base16/atlas",
    "base16/atlas.min",
    "base16/bespin",
    "base16/bespin.min",
    "base16/black-metal",
    "base16/black-metal-bathory",
    "base16/black-metal-bathory.min",
    "base16/black-metal-burzum",
    "base16/black-metal-burzum.min",
    "base16/black-metal-dark-funeral",
    "base16/black-metal-dark-funeral.min",
    "base16/black-metal-gorgoroth",
    "base16/black-metal-gorgoroth.min",
    "base16/black-metal-immortal",
    "base16/black-metal-immortal.min",
    "base16/black-metal-khold",
    "base16/black-metal-khold.min",
    "base16/black-metal-marduk",
    "base16/black-metal-marduk.min",
    "base16/black-metal-mayhem",
    "base16/black-metal-mayhem.min",
    "base16/black-metal-nile",
    "base16/black-metal-nile.min",
    "base16/black-metal-venom",
    "base16/black-metal-venom.min",
    "base16/black-metal.min",
    "base16/brewer",
    "base16/brewer.min",
    "base16/bright",
    "base16/bright.min",
    "base16/brogrammer",
    "base16/brogrammer.min",
    "base16/brush-trees",
    "base16/brush-trees-dark",
    "base16/brush-trees-dark.min",
    "base16/brush-trees.min",
    "base16/chalk",
    "base16/chalk.min",
    "base16/circus",
    "base16/circus.min",
    "base16/classic-dark",
    "base16/classic-dark.min",
    "base16/classic-light",
    "base16/classic-light.min",
    "base16/codeschool",
    "base16/codeschool.min",
    "base16/colors",
    "base16/colors.min",
    "base16/cupcake",
    "base16/cupcake.min",
    "base16/cupertino",
    "base16/cupertino.min",
    "base16/danqing",
    "base16/danqing.min",
    "base16/darcula",
    "base16/darcula.min",
    "base16/dark-violet",
    "base16/dark-violet.min",
    "base16/darkmoss",
    "base16/darkmoss.min",
    "base16/darktooth",
    "base16/darktooth.min",
    "base16/decaf",
    "base16/decaf.min",
    "base16/default-dark",
    "base16/default-dark.min",
    "base16/default-light",
    "base16/default-light.min",
    "base16/dirtysea",
    "base16/dirtysea.min",
    "base16/dracula",
    "base16/dracula.min",
    "base16/edge-dark",
    "base16/edge-dark.min",
    "base16/edge-light",
    "base16/edge-light.min",
    "base16/eighties",
    "base16/eighties.min",
    "base16/embers",
    "base16/embers.min",
    "base16/equilibrium-dark",
    "base16/equilibrium-dark.min",
    "base16/equilibrium-gray-dark",
    "base16/equilibrium-gray-dark.min",
    "base16/equilibrium-gray-light",
    "base16/equilibrium-gray-light.min",
    "base16/equilibrium-light",
    "base16/equilibrium-light.min",
    "base16/espresso",
    "base16/espresso.min",
    "base16/eva",
    "base16/eva-dim",
    "base16/eva-dim.min",
    "base16/eva.min",
    "base16/flat",
    "base16/flat.min",
    "base16/framer",
    "base16/framer.min",
    "base16/fruit-soda",
    "base16/fruit-soda.min",
    "base16/gigavolt",
    "base16/gigavolt.min",
    "base16/github",
    "base16/github.min",
    "base16/google-dark",
    "base16/google-dark.min",
    "base16/google-light",
    "base16/google-light.min",
    "base16/grayscale-dark",
    "base16/grayscale-dark.min",
    "base16/grayscale-light",
    "base16/grayscale-light.min",
    "base16/green-screen",
    "base16/green-screen.min",
    "base16/gruvbox-dark-hard",
    "base16/gruvbox-dark-hard.min",
    "base16/gruvbox-dark-medium",
    "base16/gruvbox-dark-medium.min",
    "base16/gruvbox-dark-pale",
    "base16/gruvbox-dark-pale.min",
    "base16/gruvbox-dark-soft",
    "base16/gruvbox-dark-soft.min",
    "base16/gruvbox-light-hard",
    "base16/gruvbox-light-hard.min",
    "base16/gruvbox-light-medium",
    "base16/gruvbox-light-medium.min",
    "base16/gruvbox-light-soft",
    "base16/gruvbox-light-soft.min",
    "base16/hardcore",
    "base16/hardcore.min",
    "base16/harmonic16-dark",
    "base16/harmonic16-dark.min",
    "base16/harmonic16-light",
    "base16/harmonic16-light.min",
    "base16/heetch-dark",
    "base16/heetch-dark.min",
    "base16/heetch-light",
    "base16/heetch-light.min",
    "base16/helios",
    "base16/helios.min",
    "base16/hopscotch",
    "base16/hopscotch.min",
    "base16/horizon-dark",
    "base16/horizon-dark.min",
    "base16/horizon-light",
    "base16/horizon-light.min",
    "base16/humanoid-dark",
    "base16/humanoid-dark.min",
    "base16/humanoid-light",
    "base16/humanoid-light.min",
    "base16/ia-dark",
    "base16/ia-dark.min",
    "base16/ia-light",
    "base16/ia-light.min",
    "base16/icy-dark",
    "base16/icy-dark.min",
    "base16/ir-black",
    "base16/ir-black.min",
    "base16/isotope",
    "base16/isotope.min",
    "base16/kimber",
    "base16/kimber.min",
    "base16/london-tube",
    "base16/london-tube.min",
    "base16/macintosh",
    "base16/macintosh.min",
    "base16/marrakesh",
    "base16/marrakesh.min",
    "base16/materia",
    "base16/materia.min",
    "base16/material",
    "base16/material-darker",
    "base16/material-darker.min",
    "base16/material-lighter",
    "base16/material-lighter.min",
    "base16/material-palenight",
    "base16/material-palenight.min",
    "base16/material-vivid",
    "base16/material-vivid.min",
    "base16/material.min",
    "base16/mellow-purple",
    "base16/mellow-purple.min",
    "base16/mexico-light",
    "base16/mexico-light.min",
    "base16/mocha",
    "base16/mocha.min",
    "base16/monokai",
    "base16/monokai.min",
    "base16/nebula",
    "base16/nebula.min",
    "base16/nord",
    "base16/nord.min",
    "base16/nova",
    "base16/nova.min",
    "base16/ocean",
    "base16/ocean.min",
    "base16/oceanicnext",
    "base16/oceanicnext.min",
    "base16/one-light",
    "base16/one-light.min",
    "base16/onedark",
    "base16/onedark.min",
    "base16/outrun-dark",
    "base16/outrun-dark.min",
    "base16/papercolor-dark",
    "base16/papercolor-dark.min",
    "base16/papercolor-light",
    "base16/papercolor-light.min",
    "base16/paraiso",
    "base16/paraiso.min",
    "base16/pasque",
    "base16/pasque.min",
    "base16/phd",
    "base16/phd.min",
    "base16/pico",
    "base16/pico.min",
    "base16/pop",
    "base16/pop.min",
    "base16/porple",
    "base16/porple.min",
    "base16/qualia",
    "base16/qualia.min",
    "base16/railscasts",
    "base16/railscasts.min",
    "base16/rebecca",
    "base16/rebecca.min",
    "base16/ros-pine",
    "base16/ros-pine-dawn",
    "base16/ros-pine-dawn.min",
    "base16/ros-pine-moon",
    "base16/ros-pine-moon.min",
    "base16/ros-pine.min",
    "base16/sagelight",
    "base16/sagelight.min",
    "base16/sandcastle",
    "base16/sandcastle.min",
    "base16/seti-ui",
    "base16/seti-ui.min",
    "base16/shapeshifter",
    "base16/shapeshifter.min",
    "base16/silk-dark",
    "base16/silk-dark.min",
    "base16/silk-light",
    "base16/silk-light.min",
    "base16/snazzy",
    "base16/snazzy.min",
    "base16/solar-flare",
    "base16/solar-flare-light",
    "base16/solar-flare-light.min",
    "base16/solar-flare.min",
    "base16/solarized-dark",
    "base16/solarized-dark.min",
    "base16/solarized-light",
    "base16/solarized-light.min",
    "base16/spacemacs",
    "base16/spacemacs.min",
    "base16/summercamp",
    "base16/summercamp.min",
    "base16/summerfruit-dark",
    "base16/summerfruit-dark.min",
    "base16/summerfruit-light",
    "base16/summerfruit-light.min",
    "base16/synth-midnight-terminal-dark",
    "base16/synth-midnight-terminal-dark.min",
    "base16/synth-midnight-terminal-light",
    "base16/synth-midnight-terminal-light.min",
    "base16/tango",
    "base16/tango.min",
    "base16/tender",
    "base16/tender.min",
    "base16/tomorrow",
    "base16/tomorrow-night",
    "base16/tomorrow-night.min",
    "base16/tomorrow.min",
    "base16/twilight",
    "base16/twilight.min",
    "base16/unikitty-dark",
    "base16/unikitty-dark.min",
    "base16/unikitty-light",
    "base16/unikitty-light.min",
    "base16/vulcan",
    "base16/vulcan.min",
    "base16/windows-10",
    "base16/windows-10-light",
    "base16/windows-10-light.min",
    "base16/windows-10.min",
    "base16/windows-95",
    "base16/windows-95-light",
    "base16/windows-95-light.min",
    "base16/windows-95.min",
    "base16/windows-high-contrast",
    "base16/windows-high-contrast-light",
    "base16/windows-high-contrast-light.min",
    "base16/windows-high-contrast.min",
    "base16/windows-nt",
    "base16/windows-nt-light",
    "base16/windows-nt-light.min",
    "base16/windows-nt.min",
    "base16/woodland",
    "base16/woodland.min",
    "base16/xcode-dusk",
    "base16/xcode-dusk.min",
    "base16/zenburn",
    "base16/zenburn.min",
    "brown-paper",
    "brown-paper.min",
    "codepen-embed",
    "codepen-embed.min",
    "color-brewer",
    "color-brewer.min",
    "dark",
    "dark.min",
    "default",
    "default.min",
    "devibeans",
    "devibeans.min",
    "docco",
    "docco.min",
    "far",
    "far.min",
    "felipec",
    "felipec.min",
    "foundation",
    "foundation.min",
    "github",
    "github-dark",
    "github-dark-dimmed",
    "github-dark-dimmed.min",
    "github-dark.min",
    "github.min",
    "gml",
    "gml.min",
    "googlecode",
    "googlecode.min",
    "gradient-dark",
    "gradient-dark.min",
    "gradient-light",
    "gradient-light.min",
    "grayscale",
    "grayscale.min",
    "hybrid",
    "hybrid.min",
    "idea",
    "idea.min",
    "intellij-light",
    "intellij-light.min",
    "ir-black",
    "ir-black.min",
    "isbl-editor-dark",
    "isbl-editor-dark.min",
    "isbl-editor-light",
    "isbl-editor-light.min",
    "kimbie-dark",
    "kimbie-dark.min",
    "kimbie-light",
    "kimbie-light.min",
    "lightfair",
    "lightfair.min",
    "lioshi",
    "lioshi.min",
    "magula",
    "magula.min",
    "mono-blue",
    "mono-blue.min",
    "monokai",
    "monokai-sublime",
    "monokai-sublime.min",
    "monokai.min",
    "night-owl",
    "night-owl.min",
    "nnfx-dark",
    "nnfx-dark.min",
    "nnfx-light",
    "nnfx-light.min",
    "nord",
    "nord.min",
    "obsidian",
    "obsidian.min",
    "panda-syntax-dark",
    "panda-syntax-dark.min",
    "panda-syntax-light",
    "panda-syntax-light.min",
    "paraiso-dark",
    "paraiso-dark.min",
    "paraiso-light",
    "paraiso-light.min",
    "pojoaque",
    "pojoaque.min",
    "purebasic",
    "purebasic.min",
    "qtcreator-dark",
    "qtcreator-dark.min",
    "qtcreator-light",
    "qtcreator-light.min",
    "rainbow",
    "rainbow.min",
    "routeros",
    "routeros.min",
    "school-book",
    "school-book.min",
    "shades-of-purple",
    "shades-of-purple.min",
    "srcery",
    "srcery.min",
    "stackoverflow-dark",
    "stackoverflow-dark.min",
    "stackoverflow-light",
    "stackoverflow-light.min",
    "sunburst",
    "sunburst.min",
    "tokyo-night-dark",
    "tokyo-night-dark.min",
    "tokyo-night-light",
    "tokyo-night-light.min",
    "tomorrow-night-blue",
    "tomorrow-night-blue.min",
    "tomorrow-night-bright",
    "tomorrow-night-bright.min",
    "vs",
    "vs.min",
    "vs2015",
    "vs2015.min",
    "xcode",
    "xcode.min",
    "xt256",
    "xt256.min",
]
,
  samples: [
    {
      isActive: true,
      name: "views.py",
      language: "python",
      content: `""" Views """


from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


# Create your views here.
def snippets(request: HttpRequest) -> HttpResponse:
  """Create beautiful images of your code snippets"""

  return render(request, "snippets/index.html")
`,
    },
    {
      isActive: true,
      name: "Snippets.tsx",
      language: "typescript",
      content: `import React from "react";
      
const Snippets = () => (
  <section className="grid gap-4 rounded-xl bg-white/80 p-4 ring-1 ring-white">
    <h1 className="text-4xl font-semibold">Snippets</h1>
    <p className="text-xl font-thin">
      Create beautiful images of your code snippets!
    </p>
  </section>
);

export default Snippets;
`,
    },
    {
      isActive: true,
      name: "snippets.css",
      language: "css",
      content: `.snippet {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
}
`,
    },
    {
      isActive: true,
      name: "MainActivity.kt",
      language: "kotlin",
      content: `package com.youzarsiph.snippets

import ...

class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
      SnippetsTheme {
        Column(modifier = Modifier.fillMaxSize()) {
          Text(text = "Snippets", style = MaterialTheme.typography.displayLarge)
          Text(
            text = "Create beautiful images of your code snippets!",
            style = MaterialTheme.typography.bodyLarge
          )
        }
      }
    }
  }
}
`,
    },
  ],
};

export default Constants;
