/**
 * Constants
 */

import * as Fonts from "../app/fonts";

const Constants = {
  fonts: [
    {
      label: "Fira Code",
      value: Fonts.fira_code,
    },
    {
      label: "Fira Mono",
      value: Fonts.fira_mono,
    },
    {
      label: "JetBrains Mono",
      value: Fonts.jet_brains_mono,
    },
    {
      label: "Source Code Pro",
      value: Fonts.source_code_pro,
    },
    {
      label: "IBM Plex Mono",
      value: Fonts.ibm_plex_mono,
    },
    {
      label: "Red Hat Mono",
      value: Fonts.red_hat_mono,
    },
    {
      label: "Ubuntu Mono",
      value: Fonts.ubuntu_mono,
    },
    {
      label: "Nova Mono",
      value: Fonts.nova_mono,
    },
    {
      label: "Roboto Mono",
      value: Fonts.roboto_mono,
    },
    {
      label: "Share Tech Mono",
      value: Fonts.share_tech_mono,
    },
  ],
  highlights: [
    "a11y-dark",
    "a11y-light",
    "agate",
    "an-old-hope",
    "androidstudio",
    "arduino-light",
    "arta",
    "ascetic",
    "atom-one-dark-reasonable",
    "atom-one-dark",
    "atom-one-light",
    "base16/3024",
    "base16/apathy",
    "base16/apprentice",
    "base16/ashes",
    "base16/atelier-cave-light",
    "base16/atelier-cave",
    "base16/atelier-dune-light",
    "base16/atelier-dune",
    "base16/atelier-estuary-light",
    "base16/atelier-estuary",
    "base16/atelier-forest-light",
    "base16/atelier-forest",
    "base16/atelier-heath-light",
    "base16/atelier-heath",
    "base16/atelier-lakeside-light",
    "base16/atelier-lakeside",
    "base16/atelier-plateau-light",
    "base16/atelier-plateau",
    "base16/atelier-savanna-light",
    "base16/atelier-savanna",
    "base16/atelier-seaside-light",
    "base16/atelier-seaside",
    "base16/atelier-sulphurpool-light",
    "base16/atelier-sulphurpool",
    "base16/atlas",
    "base16/bespin",
    "base16/black-metal-bathory",
    "base16/black-metal-burzum",
    "base16/black-metal-dark-funeral",
    "base16/black-metal-gorgoroth",
    "base16/black-metal-immortal",
    "base16/black-metal-khold",
    "base16/black-metal-marduk",
    "base16/black-metal-mayhem",
    "base16/black-metal-nile",
    "base16/black-metal-venom",
    "base16/black-metal",
    "base16/brewer",
    "base16/bright",
    "base16/brogrammer",
    "base16/brush-trees-dark",
    "base16/brush-trees",
    "base16/chalk",
    "base16/circus",
    "base16/classic-dark",
    "base16/classic-light",
    "base16/codeschool",
    "base16/colors",
    "base16/cupcake",
    "base16/cupertino",
    "base16/danqing",
    "base16/darcula",
    "base16/dark-violet",
    "base16/darkmoss",
    "base16/darktooth",
    "base16/decaf",
    "base16/default-dark",
    "base16/default-light",
    "base16/dirtysea",
    "base16/dracula",
    "base16/edge-dark",
    "base16/edge-light",
    "base16/eighties",
    "base16/embers",
    "base16/equilibrium-dark",
    "base16/equilibrium-gray-dark",
    "base16/equilibrium-gray-light",
    "base16/equilibrium-light",
    "base16/espresso",
    "base16/eva-dim",
    "base16/eva",
    "base16/flat",
    "base16/framer",
    "base16/fruit-soda",
    "base16/gigavolt",
    "base16/github",
    "base16/google-dark",
    "base16/google-light",
    "base16/grayscale-dark",
    "base16/grayscale-light",
    "base16/green-screen",
    "base16/gruvbox-dark-hard",
    "base16/gruvbox-dark-medium",
    "base16/gruvbox-dark-pale",
    "base16/gruvbox-dark-soft",
    "base16/gruvbox-light-hard",
    "base16/gruvbox-light-medium",
    "base16/gruvbox-light-soft",
    "base16/hardcore",
    "base16/harmonic16-dark",
    "base16/harmonic16-light",
    "base16/heetch-dark",
    "base16/heetch-light",
    "base16/helios",
    "base16/hopscotch",
    "base16/horizon-dark",
    "base16/horizon-light",
    "base16/humanoid-dark",
    "base16/humanoid-light",
    "base16/ia-dark",
    "base16/ia-light",
    "base16/icy-dark",
    "base16/ir-black",
    "base16/isotope",
    "base16/kimber",
    "base16/london-tube",
    "base16/macintosh",
    "base16/marrakesh",
    "base16/materia",
    "base16/material-darker",
    "base16/material-lighter",
    "base16/material-palenight",
    "base16/material-vivid",
    "base16/material",
    "base16/mellow-purple",
    "base16/mexico-light",
    "base16/mocha",
    "base16/monokai",
    "base16/nebula",
    "base16/nord",
    "base16/nova",
    "base16/ocean",
    "base16/oceanicnext",
    "base16/one-light",
    "base16/onedark",
    "base16/outrun-dark",
    "base16/papercolor-dark",
    "base16/papercolor-light",
    "base16/paraiso",
    "base16/pasque",
    "base16/phd",
    "base16/pico",
    "base16/pop",
    "base16/porple",
    "base16/qualia",
    "base16/railscasts",
    "base16/rebecca",
    "base16/ros-pine-dawn",
    "base16/ros-pine-moon",
    "base16/ros-pine",
    "base16/sagelight",
    "base16/sandcastle",
    "base16/seti-ui",
    "base16/shapeshifter",
    "base16/silk-dark",
    "base16/silk-light",
    "base16/snazzy",
    "base16/solar-flare-light",
    "base16/solar-flare",
    "base16/solarized-dark",
    "base16/solarized-light",
    "base16/spacemacs",
    "base16/summercamp",
    "base16/summerfruit-dark",
    "base16/summerfruit-light",
    "base16/synth-midnight-terminal-dark",
    "base16/synth-midnight-terminal-light",
    "base16/tango",
    "base16/tender",
    "base16/tomorrow-night",
    "base16/tomorrow",
    "base16/twilight",
    "base16/unikitty-dark",
    "base16/unikitty-light",
    "base16/vulcan",
    "base16/windows-10-light",
    "base16/windows-10",
    "base16/windows-95-light",
    "base16/windows-95",
    "base16/windows-high-contrast-light",
    "base16/windows-high-contrast",
    "base16/windows-nt-light",
    "base16/windows-nt",
    "base16/woodland",
    "base16/xcode-dusk",
    "base16/zenburn",
    "brown-paper",
    "codepen-embed",
    "color-brewer",
    "dark",
    "default",
    "devibeans",
    "docco",
    "far",
    "felipec",
    "foundation",
    "github-dark-dimmed",
    "github-dark",
    "github",
    "gml",
    "googlecode",
    "gradient-dark",
    "gradient-light",
    "grayscale",
    "hybrid",
    "idea",
    "intellij-light",
    "ir-black",
    "isbl-editor-dark",
    "isbl-editor-light",
    "kimbie-dark",
    "kimbie-light",
    "lightfair",
    "lioshi",
    "magula",
    "mono-blue",
    "monokai-sublime",
    "monokai",
    "night-owl",
    "nnfx-dark",
    "nnfx-light",
    "nord",
    "obsidian",
    "panda-syntax-dark",
    "panda-syntax-light",
    "paraiso-dark",
    "paraiso-light",
    "pojoaque",
    "pojoaque.jpg",
    "purebasic",
    "qtcreator-dark",
    "qtcreator-light",
    "rainbow",
    "routeros",
    "school-book",
    "shades-of-purple",
    "srcery",
    "stackoverflow-dark",
    "stackoverflow-light",
    "sunburst",
    "tokyo-night-dark",
    "tokyo-night-light",
    "tomorrow-night-blue",
    "tomorrow-night-bright",
    "vs",
    "vs2015",
    "xcode",
    "xt256",
  ],
  container: {
    size: [
      {
        name: "Auto",
        value: {
          width: "max-content",
          height: "max-content",
        },
      },
      {
        name: "Full screen",
        value: {
          width: "100%",
          height: "100%",
        },
      },
      {
        name: "Post",
        value: { width: 960, height: 540 },
      },
      {
        name: "Header",
        value: { width: 1500, height: 500 },
      },
      {
        name: "Instagram Post",
        value: { width: 720, height: 720 },
      },
      ,
      {
        name: "Story / Reel",
        value: { width: 540, height: 960 },
      },
      {
        name: "Thumbnail",
        value: { width: 1280, height: 720 },
      },
    ],
    bg: {
      type: [
        { name: "linear", value: "bg-gradient-to-tr" },
        { name: "radial", value: "bg-gradient-radial" },
        { name: "conic", value: "bg-gradient-conic" },
      ],
      colors: [
        "bg-transparent ring-1 ring-white dark:ring-stone-900/95",
        "from-blue-500 to-blue-300 ring-1 ring-blue-500 dark:from-blue-950 dark:to-blue-700 dark:ring-blue-950",
        "from-green-500 to-green-300 ring-1 ring-green-500 dark:from-green-950 dark:to-green-700 dark:ring-green-950",
        "from-rose-500 to-rose-300 ring-1 ring-rose-500 dark:from-rose-950 dark:to-rose-700 dark:ring-rose-950",
        "from-indigo-500 to-indigo-300 ring-1 ring-indigo-500 dark:from-indigo-950 dark:to-indigo-700 dark:ring-indigo-950",
        "from-violet-500 to-violet-300 ring-1 ring-violet-500 dark:from-violet-950 dark:to-violet-700 dark:ring-violet-950",
        "from-purple-500 to-purple-300 ring-1 ring-purple-500 dark:from-purple-950 dark:to-purple-700 dark:ring-purple-950",
        "from-lime-500 to-lime-300 ring-1 ring-lime-500 dark:from-lime-950 dark:to-lime-700 dark:ring-lime-950",
        "from-yellow-500 to-yellow-300 ring-1 ring-yellow-500 dark:from-yellow-950 dark:to-yellow-700 dark:ring-yellow-950",
        "from-sky-500 to-sky-300 ring-1 ring-sky-500 dark:from-sky-950 dark:to-sky-700 dark:ring-sky-950",
        "from-teal-500 to-teal-300 ring-1 ring-teal-500 dark:from-teal-950 dark:to-teal-700 dark:ring-teal-950",
        "from-cyan-500 to-cyan-300 ring-1 ring-cyan-500 dark:from-cyan-950 dark:to-cyan-700 dark:ring-cyan-950",
        "from-amber-500 to-amber-300 ring-1 ring-amber-500 dark:from-amber-950 dark:to-amber-700 dark:ring-amber-950",
        "from-emerald-500 to-emerald-300 ring-1 ring-emerald-500 dark:from-emerald-950 dark:to-emerald-700 dark:ring-emerald-950",
        "from-fuchsia-500 to-fuchsia-300 ring-1 ring-fuchsia-500 dark:from-fuchsia-950 dark:to-fuchsia-700 dark:ring-fuchsia-950",
        "from-orange-500 to-orange-300 ring-1 ring-orange-500 dark:from-orange-950 dark:to-orange-700 dark:ring-orange-950",
        "from-slate-500 to-slate-300 ring-1 ring-slate-500 dark:from-slate-950 dark:to-slate-700 dark:ring-slate-950",
        "from-stone-500 to-stone-300 ring-1 ring-stone-500 dark:from-stone-950 dark:to-stone-700 dark:ring-stone-950",
        "from-sky-400 to-lime-400 ring-1 ring-sky-400 dark:from-sky-700 dark:to-lime-700 dark:ring-sky-700",
        "from-sky-400 to-pink-400 ring-1 ring-sky-400 dark:from-sky-700 dark:to-pink-800 dark:ring-sky-700",
        "from-lime-300 to-orange-300 ring-1 ring-lime-300 dark:from-lime-700 dark:to-orange-600 dark:ring-lime-700",
        "from-green-400 to-teal-400 ring-1 ring-green-400 dark:from-green-700 dark:to-teal-600 dark:ring-green-700",
        "from-green-400 to-amber-300 ring-1 ring-green-400 dark:from-green-700 dark:to-amber-600 dark:ring-green-700",
        "from-sky-300 to-pink-300 ring-1 ring-sky-300 dark:from-sky-700 dark:to-pink-600 dark:ring-sky-700",
        "from-green-400 to-sky-400 ring-1 ring-green-400 dark:from-green-600 dark:to-sky-500 dark:ring-green-600",
        "from-emerald-400 to-sky-300 ring-1 ring-emerald-400 dark:from-emerald-700 dark:to-sky-600 dark:ring-emerald-700",
        "from-lime-300 to-green-400 ring-1 ring-lime-300 dark:from-lime-700 dark:to-green-600 dark:ring-lime-700",
        "from-cyan-300 to-emerald-400 ring-1 ring-cyan-300 dark:from-cyan-800 dark:to-emerald-700 dark:ring-cyan-800",
        "from-cyan-200 to-pink-400 ring-1 ring-cyan-200 dark:from-cyan-700 dark:to-pink-600 dark:ring-cyan-700",
        "from-red-400 to-orange-300 ring-1 ring-red-400 dark:from-red-600 dark:to-orange-500 dark:ring-red-600",
        "from-orange-400 to-orange-100 ring-1 ring-orange-400 dark:from-red-700 dark:to-red-600 dark:ring-red-700",
        "from-orange-200 to-sky-400 ring-1 ring-orange-200 dark:from-orange-800 dark:to-sky-700 dark:ring-orange-800",
        "from-orange-200 to-red-300 ring-1 ring-orange-200 dark:from-orange-600 dark:to-red-500 dark:ring-orange-600",
        "from-lime-200 to-pink-400 ring-1 ring-lime-200 dark:from-lime-600 dark:to-pink-500 dark:ring-lime-600",
        "from-sky-200 to-pink-300 ring-1 ring-sky-200 dark:from-sky-600 dark:to-pink-500 dark:ring-sky-600",
      ],
      directions: [
        { name: "To top right", value: "bg-gradient-to-tr" },
        { name: "To right", value: "bg-gradient-to-r" },
        { name: "To top", value: "bg-gradient-to-t" },
        { name: "To left", value: "bg-gradient-to-l" },
        { name: "To bottom", value: "bg-gradient-to-b" },
        { name: "To top left", value: "bg-gradient-to-tl" },
        { name: "To bottom left", value: "bg-gradient-to-bl" },
        { name: "To bottom right", value: "bg-gradient-to-br" },
      ],
    },
    padding: [
      { label: "16", value: "p-4" },
      { label: "32", value: "p-8" },
      { label: "64", value: "p-16" },
      { label: "128", value: "p-32" },
    ],
  },
  formats: ["svg", "png", "jpeg"],
  samples: [
    {
      active: true,
      title: "views.py",
      language: "python",
      code: `""" Views """


from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


# Create your views here.
def snippets(request: HttpRequest) -> HttpResponse:
  """Create beautiful images of your code snippets"""

  return render(request, "snippets/index.html")
`,
    },
    {
      active: true,
      title: "Snippets.tsx",
      language: "typescript",
      code: `import React from "react";
      
const Snippets = () => (
  <section className="grid gap-4 rounded-xl bg-white/80 p-4 ring-1 ring-white">
    <h1 className="text-4xl font-semibold">Snippets</h1>
    <p className="text-xl font-thin">
      Create beautiful images of your code snippets!
    </p>
  </section>
);

export default Snippets;
`,
    },
    {
      active: true,
      title: "snippets.css",
      language: "css",
      code: `.snippet {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
}
`,
    },
    {
      active: true,
      title: "MainActivity.kt",
      language: "kotlin",
      code: `package com.youzarsiph.snippets

import ...

class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
      SnippetsTheme {
        Column(modifier = Modifier.fillMaxSize()) {
          Text(text = "Snippets", style = MaterialTheme.typography.displayLarge)
          Text(
            text = "Create beautiful images of your code snippets!",
            style = MaterialTheme.typography.bodyLarge
          )
        }
      }
    }
  }
}
`,
    },
  ],
};

export default Constants;
